### ISSUE TITLE
Add support to V9 Keybinding

### ISSUE THREAD

**Issue by jocolamarco** [digitalpacman/foundryvtt-pf2e-reach-templates#4]
Nothing happens when pressing 'r' and the following error message is shown in the console log:

![imagem](https://user-images.githubusercontent.com/45291719/149766045-1109e38c-be19-4785-b1f9-d97b9c163142.png)

Versions:
- FVTT **9.242**
- PF2e **3.2.1.10003**
-  foundryvtt-pf2e-reach-templates **1.0.2**

**Comment by Tridus** [comment]
This particular issue isn't with the keybinding, it's that a bunch of things were moved around in v9 and thus the locations changed. In this case, e.getFlag doesn't work, but e.document.getFlag does.

I've been looking into it in some spare time, and if you fix the calls to getFlag, setFlag, unsetFlag (all with document.getFlag, etc), and replace the Drawing.create() (which doesn't exist anymore), it does work again. 

Drawing.create has to be replaced like this:
DrawingDocument.create([{the existing properties in the call}], {parent: canvas.scene})

The keybindings themselves should also be updated to foundry v9 because that lets you customize them in the UI, but that isn't required to get the module running.

I've got a working local copy, going to see if I can clean it up if the author doesn't want to do it.

**Comment by digitalpacman** [comment]
Cool. I'll look into fixing it thanks for the response @Tridus

**Comment by Tridus** [comment]
To be more specific, the things I changed were this.

Drawing.create needs to be DrawingDocument.create:

const [o] = await DrawingDocument.create([{
                            type: CONST.DRAWING_TYPES.FREEHAND,
                            author: game.user._id,
                            x: e.x - (t / 5) * canvas.scene.data.grid,
                            y: e.y - (t / 5) * canvas.scene.data.grid,
                            fillType: CONST.DRAWING_FILL_TYPES.NONE,
                            strokeWidth: 4,
                            strokeColor: n(),
                            strokeAlpha: 0.75,
                            points: r.map(([e, t]) => [e * canvas.scene.data.grid, t * canvas.scene.data.grid]),
                        }], {parent: canvas.scene});


e.SetFlag (and getFlag/unsetFlag) can be e.document.setFlag

Those changes appear to get it working again in my limited testing. I didn't do things with the keybinds, but the new v9 keybinding system appears to be pretty easy to implement and also creates a UI element in the Foundry keybindings to edit it.

**Comment by digitalpacman** [comment]
This has been a lot harder than expected. Fix one thing and another thing is broken. Seems like everything has changed. Token attacher isn't working anymore, drawing isn't working, and updating the server isn't working.

**Comment by digitalpacman** [comment]
This should be fixed. It's published. Just update.

@jocolamarco 
@Tridus
